<?php  
	require('template/header.phtml');

	if (isset($_SESSION['user_type']) && $_SESSION['user_type'] == 'admin') {
		header('location: dashboard.php');
	}

	require('../Models/User.php'); 

	$loginObj = new User();
	
	$msg = $user = ''; 


	if(isset ($_POST['submit'])){
		$user = $_POST['user'];
        $userpass = md5($_POST['password']);

		if($loginObj->emailExists($user, 'admin')) {
			$user = $loginObj->login($user, $userpass, 'admin');
		    if($user){ 
	            $row = mysqli_fetch_assoc($user);	 
	            session_start();    	
		    	$_SESSION['user_id'] = $row['id'];
	            $_SESSION['user_name'] = $row['name'];
	            $_SESSION['user_email'] = $row['email'];
	            $_SESSION['user_type'] = 'admin';
		       	header("location:dashboard.php");
	        }else{
	            $msg = "Invalid Password.";
	        }	
		}else{
			$msg = "Email does not exists";
		}


			
	}
?>

<?php 
	if (isset($_GET['msg'])) {
		echo "<div class='success'>$_GET[msg]</div>";
	}
?>

<form action="" method="post" class="form">

	<div class="panel"  style="width:70%; box-shadow: 10px 10px 5px #eee; margin: 100px auto; background: #fff;">

		<h2 class="panel-title">ADMIN LOGIN</h2>
		
		<?php 
			if($msg != null) {
				echo "<div class='error'>$msg</div>";
			}
		?>
		
		<div class="form-group">			
			<label for="">Email<span>*</span></label>
			<input type="text" name="user" placeholder="Enter email" value="<?= $user; ?>" required class="form-control">			
		</div>
		<div class="form-group">	
			<label for="">Password<span>*</span></label>
			<input type="password" name="password" placeholder="Enter password" required class="form-control">
		</div>
		<div class="form-group button-input">			
			<input type="submit" value="Login" name="submit" class="btn">
		</div>

	</div>
</form>

<?php  
	require('template/footer.phtml'); 
?>

