<?php require('template/header.phtml') ?>

<div class="banner">
	<img src="images/home/banner6.jpg" alt="" width="100%">
</div>

<section class="home-section section-block">
	<div class="left">
		<div class="gallery">
			<h2 class="home-title">GALLERY</h2>
			<div class="gallery-images">
				<img src="images/home/3.jpg" alt="">
				<img src="images/home/1.jpg" alt="">
				<img src="images/home/5.jpg" alt="">
				<img src="images/home/4.jpg" alt="">
				<img src="images/home/6.jpg" alt="">
				<img src="images/home/7.jpg" alt="">
			</div>
		</div>
	</div>
	<div class="right">
		<div class="gallery offer-box">
			<h2 class="home-title">Seasonal Offers</h2>
				<p class="home-subtitle">Hurry Up ! grab the offers fast.</p>

			<div class="">
				<div class="offer">
					<img src="images/home/s1.jpg" alt="">
					<img src="images/home/s2.png" alt="">
				</div>
			</div>
		</div>
	</div>
</section>	
	
<section class="banner  section-block">
	<h2 class="home-title">Our Memories</h2>
	<img src="images/home/banner3.jpg" alt="" width="100%">

	<!-- Videos part---	 -->

	<div class="video-block">
		<div class="in-video">
			<video width="100%" height="" controls>
			  <source src="images/videos/1.mp4" type="video/mp4">
			  Your browser does not support the video tag.
			</video>
		</div>
		<div class="in-video">
			<video width="100%" height="" controls>
			  <source src="images/videos/2.mp4" type="video/mp4">
			  Your browser does not support the video tag.
			</video>
		</div>
	</div>

</section>	

<?php require('template/footer.phtml') ?>