</div>

<div class="map-container">
	<h2 class="home-title">Our Location</h2>

	<div class="mapouter"><div class="gmap_canvas"><iframe width="100%" height="333" id="gmap_canvas" src="https://maps.google.com/maps?q=sainik%20colony%2C%20jamu&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net/en/">embedgooglemap.net</a></div><style>.mapouter{position:relative;text-align:right;height:333px;width:100%;}.gmap_canvas {overflow:hidden;background:none!important;height:333px;width:100%;}</style></div>
</div>


<footer>
	<div class="contact-grid" id="contact">
		<div class="contact-box">
			<h1>Reach Us</h1>
			<p>Address Line 1<br>Address Line 1<br></p>
		</div>
		<div class="contact-box">
			<h1>Contact Us</h1>
			<p><b>Tel: </b>023565525689</p>
			<p><b>E: </b><span style="text-transform:lowercase;">abc@gmail.com</span></p>
		</div>
		<div class="contact-box">
			<h1>Opening Hours</h1>
			<p>Monday to Sunday</p>
			<p>12:00 pm - 12:00 am</p>
		</div>
	</div>

	<div class="bottom-nav">
		<p>&copy; Copyright Cafe Coffee Day. All Rights reserved.</p>
		<ul class="links">
			<li><a href=""><img src="images/email.png" alt="" class="bottom-img"></a></li>
			<li><a href=""><img src="images/insta.png" alt="" class="bottom-img"></a></li>
			<li><a href=""><img src="images/whatsapp.png" alt="" class="bottom-img"></a></li>
		</ul>
	</div>

</footer>

<script>
	function showMenu(){
		if(document.getElementById('chckMenu').checked == true){
			document.getElementById('navbar').style.display = "flex";
		}else{
			document.getElementById('navbar').style.display = "none";
		}
	}
	function drop(menu){
		
		allMenus = document.querySelectorAll('.dropmenu');
		allMenus.forEach(a=>a.classList.add("hideMenuOnClick"));

		document.getElementById(menu).classList.remove("hideMenuOnClick");
		document.getElementById(menu).classList.toggle("showMenuOnClick");
	}
</script>
</body>
</html>